name: questdb
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - polars
  - osmnx
  - toml
  - hydra-core
  - python-dotenv
  - h3-py
  - requests
  - asyncpg
  - pyarrow
  - fastapi
  - sqlalchemy
  - uvicorn
  - psycopg2
  - pip:
    - questdb