colnames:
  ap_id: ap_id
  session_id: session_id
  lon: longitude
  lat: latitude
  time: timestamp
  band: band
  channel: channel
  state: state
  region: region

db:
  questdb:
    auth:
      username: admin
      password: quest
      host: localhost
      db: qdb
    params:
      ingestion_protocol: http
      ingestion_port: 9000
      query_port: 8812
      table_name: wifi
      indexes:
        # - ${colnames.ap_id}
        - ${colnames.channel}
        - ${colnames.band}
        - ${colnames.state}
        - ${colnames.region}
  clickhouse:
    auth:
      username: default
      password: ""
      host: localhost
      port: 8123
    params:
      table_name: wifi